### ISSUE TITLE
:read-only and :read-write

### ISSUE THREAD

**Issue by arextar** [chjj/zest#8]
> An element whose contents are not user-alterable is :read-only.

I think read-only should look at the contenteditable attribute and whether or not the element is an input element. Also: a disabled text input could be considered read-only.

**Comment by arextar** [comment]
``` js
 ':read-only': function(el) {
    var nodeName = el.nodeName;
    return (nodeName !== "INPUT" && nodeName !== "TEXTAREA" || el.disabled) && el.getAttribute("contenteditable") === null;
  }
```

A quick test of the function: http://jsfiddle.net/nG6bu/1/embedded/result/

**Comment by arextar** [comment]
I can open a pull request if you think this is a good idea

**Comment by chjj** [comment]
Looks good to me.
